/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_pos;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class POS extends javax.swing.JFrame {

  double nTotal = 0, nSubTotal = 0, nPreviousPrice = 0;
  String strPreviousDrink;
    
	// Service Fee Rate
	final double SF_RATE = 0.020;
    
	// VAT rate
	final double VAT_RATE = 0.075;                                   
        DecimalFormat PRICE_FORMAT = new DecimalFormat("Php ###.##");
    // flag, if the user does not enter a number in the dialog
	final int DIALOG_NOT_NUM = -1;                            

    // flag, if the user cancels the dialog
	final int DIALOG_CANCEL = -2;       
  
    public POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        btnVodka = new javax.swing.JButton();
        btnBeer = new javax.swing.JButton();
        btnTequila = new javax.swing.JButton();
        btnCancelPrevious = new javax.swing.JButton();
        btnNewOrder = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        radIce = new javax.swing.JRadioButton();
        radSomeIce = new javax.swing.JRadioButton();
        radNoIce = new javax.swing.JRadioButton();
        lblPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3M-DA Bar");
        setBackground(new java.awt.Color(204, 255, 204));
        setFont(new java.awt.Font("Magneto", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(204, 255, 204));
        setResizable(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 204));

        txtBill.setEditable(false);
        txtBill.setColumns(20);
        txtBill.setRows(5);
        jScrollPane1.setViewportView(txtBill);

        btnVodka.setBackground(new java.awt.Color(255, 255, 102));
        btnVodka.setText("VODKA");
        btnVodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVodkaActionPerformed(evt);
            }
        });

        btnBeer.setBackground(new java.awt.Color(153, 255, 153));
        btnBeer.setText("BEER");
        btnBeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeerActionPerformed(evt);
            }
        });

        btnTequila.setBackground(new java.awt.Color(255, 153, 153));
        btnTequila.setText("TEQUILA");
        btnTequila.setToolTipText("");
        btnTequila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTequilaActionPerformed(evt);
            }
        });

        btnCancelPrevious.setBackground(new java.awt.Color(0, 153, 255));
        btnCancelPrevious.setText("CANCEL PREVIOUS");
        btnCancelPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPreviousActionPerformed(evt);
            }
        });

        btnNewOrder.setBackground(new java.awt.Color(0, 153, 255));
        btnNewOrder.setText("NEW ORDER");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnCalculate.setBackground(new java.awt.Color(0, 153, 255));
        btnCalculate.setText("CALCULATE");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        radIce.setText("With a lot of Ice");
        radIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radIceActionPerformed(evt);
            }
        });

        radSomeIce.setSelected(true);
        radSomeIce.setText("With some Ice");

        radNoIce.setText("Without Ice");

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_pos/drink.jpg"))); // NOI18N
        lblPic.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVodka, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTequila, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radSomeIce)
                                    .addComponent(radNoIce)
                                    .addComponent(radIce))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTequila, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVodka, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(radIce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radSomeIce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radNoIce))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeerActionPerformed

        addItem("Beer" + spaces(46), 150);
        btnCalculate.setEnabled(true);
        btnCancelPrevious.setEnabled(true);
        repaint();
    }//GEN-LAST:event_btnBeerActionPerformed

    private void btnTequilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTequilaActionPerformed
         addItem("Tequila" + spaces(41), 250);
            btnCalculate.setEnabled(true);
            btnCancelPrevious.setEnabled(true);
            repaint();
    }//GEN-LAST:event_btnTequilaActionPerformed

    private void btnVodkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVodkaActionPerformed
        addItem("Vodka" + spaces(43), 200);
            btnCalculate.setEnabled(true);
            btnCancelPrevious.setEnabled(true);
            repaint();
    }//GEN-LAST:event_btnVodkaActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
       initializeBill();
            repaint();
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        double nPST = nTotal * SF_RATE;
            double nGST = (nTotal + nPST) * VAT_RATE;
            nSubTotal = nTotal + nPST + nGST;

            txtBill.setText(txtBill.getText() + "\n" +
                "     " + "Total: " + spaces(41) + PRICE_FORMAT.format(nTotal) + "\n");

            txtBill.setText(txtBill.getText()  +
                "     " + "Service Fee: " + spaces(29) + PRICE_FORMAT.format(nPST) + "\n");

            txtBill.setText(txtBill.getText()  +
                "     " + "VAT: " + spaces(43) + PRICE_FORMAT.format(nGST) + "\n");

            txtBill.setText(txtBill.getText()  +
                "     " + "Subtotal: " + spaces(35) + 
				PRICE_FORMAT.format(nSubTotal) + "\n");

            btnCalculate.setEnabled(false);
            btnCancelPrevious.setEnabled(false);
            btnBeer.setEnabled(false);
            btnTequila.setEnabled(false);
            btnVodka.setEnabled(false);

            // get amount paid by client
            double nAnswer = getAmount();

            // if the cancel button is pressed, reinitialize.
            if (nAnswer == DIALOG_CANCEL)
                initializeBill();
            else
            {
                // while the client gives an insufficent amount, ask again
                while (nAnswer < nSubTotal)
                {
                    if (nAnswer != DIALOG_NOT_NUM)
                        JOptionPane.showMessageDialog(null,
                            "The amount paid must be at least " + 
							PRICE_FORMAT.format(nSubTotal),
                            "Insufficent Amount", JOptionPane.OK_OPTION);
                    nAnswer = getAmount();
                    if (nAnswer == DIALOG_CANCEL)
                    {
                        initializeBill();
                        return;
                    }
                }

                txtBill.setText(txtBill.getText() + "\n" +
                    "     " + "Paid: " + spaces(42) + 
					PRICE_FORMAT.format(nAnswer));
                txtBill.setText(txtBill.getText() + "\n" +
                    "     " + "Returned: " + spaces(33) + 
					PRICE_FORMAT.format(nAnswer-nSubTotal));
            }
            repaint();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCancelPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPreviousActionPerformed
         txtBill.setText(txtBill.getText() + "\n" +
                "     " + strPreviousDrink + 
				spaces(40 - strPreviousDrink.length()) + "-" +
                PRICE_FORMAT.format(nPreviousPrice) + "\n" +  "     (Canceled)\n");
            nTotal -= nPreviousPrice;
            btnCancelPrevious.setEnabled(false);
            repaint();
    }//GEN-LAST:event_btnCancelPreviousActionPerformed

    private void radIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radIceActionPerformed
   
    }//GEN-LAST:event_radIceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new POS().setVisible(true);
        });
        
    }
     void initializeBill()
    {
        nTotal = 0;
        txtBill.setText(spaces(40) + "- 3M-DA Bar -\n");
        btnBeer.setEnabled(true);
        btnTequila.setEnabled(true);
        btnVodka.setEnabled(true);
    }
    double getAmount()
    {
        try {
                String strAnswer = JOptionPane.showInputDialog(null, 
					"Please enter the amount paid: ",
                    "Amount Paid", JOptionPane.OK_CANCEL_OPTION);
                return Double.parseDouble(strAnswer);
            }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter a number.",
                    "Number Format Exception", JOptionPane.OK_OPTION);
            return -1;
        }
        catch (NullPointerException e)
        {
            System.out.println("Transaction Canceled");
            return -2;
        }
    }
    void addItem(String drink, double price)
    {
        String strIce = "";
        if (radIce.isSelected())
            strIce = "(" + radIce.getText() + ")";
        else if (radSomeIce.isSelected())
            strIce = "(" + radSomeIce.getText() + ")";
        else
            strIce = "(" + radNoIce.getText() + ")";


        txtBill.setText(txtBill.getText() + "\n" +
                "     " + drink + PRICE_FORMAT.format(price) + "\n" +
                "     " + strIce + "\n");
        strPreviousDrink = drink;
        nPreviousPrice = price;
        nTotal += price;
    }
String spaces(int num)
    {
        String str = "";
        for (int i = 0; i < num; i++)
            str += " ";
        return str;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeer;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCancelPrevious;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnTequila;
    private javax.swing.JButton btnVodka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPic;
    private javax.swing.JRadioButton radIce;
    private javax.swing.JRadioButton radNoIce;
    private javax.swing.JRadioButton radSomeIce;
    private javax.swing.JTextArea txtBill;
    // End of variables declaration//GEN-END:variables
}
